# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_principal.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Principal(object):
    def setupUi(self, Principal):
        Principal.setObjectName(_fromUtf8("Principal"))
        Principal.resize(718, 517)
        self.centralwidget = QtGui.QWidget(Principal)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_conf_gerais = QtGui.QWidget()
        self.tab_conf_gerais.setObjectName(_fromUtf8("tab_conf_gerais"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_conf_gerais)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.grpMain = QtGui.QGroupBox(self.tab_conf_gerais)
        self.grpMain.setTitle(_fromUtf8(""))
        self.grpMain.setObjectName(_fromUtf8("grpMain"))
        self.gridLayout = QtGui.QGridLayout(self.grpMain)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.grpFornACCERA = QtGui.QGroupBox(self.grpMain)
        self.grpFornACCERA.setObjectName(_fromUtf8("grpFornACCERA"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpFornACCERA)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.bt_add_forn_accera = QtGui.QToolButton(self.grpFornACCERA)
        self.bt_add_forn_accera.setObjectName(_fromUtf8("bt_add_forn_accera"))
        self.gridLayout_2.addWidget(self.bt_add_forn_accera, 0, 1, 1, 1)
        self.cmb_fornecedor_accera = QtGui.QComboBox(self.grpFornACCERA)
        self.cmb_fornecedor_accera.setEditable(True)
        self.cmb_fornecedor_accera.setMaxVisibleItems(5)
        self.cmb_fornecedor_accera.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cmb_fornecedor_accera.setObjectName(_fromUtf8("cmb_fornecedor_accera"))
        self.gridLayout_2.addWidget(self.cmb_fornecedor_accera, 0, 0, 1, 1)
        self.tb_fornecedores = QtGui.QTableWidget(self.grpFornACCERA)
        self.tb_fornecedores.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tb_fornecedores.setFrameShadow(QtGui.QFrame.Sunken)
        self.tb_fornecedores.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tb_fornecedores.setAlternatingRowColors(True)
        self.tb_fornecedores.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tb_fornecedores.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tb_fornecedores.setShowGrid(True)
        self.tb_fornecedores.setObjectName(_fromUtf8("tb_fornecedores"))
        self.tb_fornecedores.setColumnCount(2)
        self.tb_fornecedores.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tb_fornecedores.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tb_fornecedores.setHorizontalHeaderItem(1, item)
        self.tb_fornecedores.horizontalHeader().setMinimumSectionSize(33)
        self.tb_fornecedores.horizontalHeader().setSortIndicatorShown(True)
        self.tb_fornecedores.verticalHeader().setSortIndicatorShown(True)
        self.gridLayout_2.addWidget(self.tb_fornecedores, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.grpFornACCERA, 1, 0, 1, 1)
        self.grpGeral = QtGui.QGroupBox(self.grpMain)
        self.grpGeral.setObjectName(_fromUtf8("grpGeral"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grpGeral)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.grpGeral)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.dte_hora = QtGui.QDateTimeEdit(self.grpGeral)
        self.dte_hora.setCurrentSection(QtGui.QDateTimeEdit.HourSection)
        self.dte_hora.setCalendarPopup(False)
        self.dte_hora.setTimeSpec(QtCore.Qt.LocalTime)
        self.dte_hora.setObjectName(_fromUtf8("dte_hora"))
        self.gridLayout_3.addWidget(self.dte_hora, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.grpGeral)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.txt_cod_distrbuidor = QtGui.QLineEdit(self.grpGeral)
        self.txt_cod_distrbuidor.setMaxLength(14)
        self.txt_cod_distrbuidor.setObjectName(_fromUtf8("txt_cod_distrbuidor"))
        self.gridLayout_3.addWidget(self.txt_cod_distrbuidor, 3, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.grpGeral)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 4, 0, 1, 1)
        self.txt_local_gravar_arquivos = QtGui.QLineEdit(self.grpGeral)
        self.txt_local_gravar_arquivos.setObjectName(_fromUtf8("txt_local_gravar_arquivos"))
        self.gridLayout_3.addWidget(self.txt_local_gravar_arquivos, 5, 0, 1, 1)
        self.gridLayout.addWidget(self.grpGeral, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.grpMain, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_conf_gerais, _fromUtf8(""))
        self.tab_conf_accera = QtGui.QWidget()
        self.tab_conf_accera.setObjectName(_fromUtf8("tab_conf_accera"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_conf_accera)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.grp_accera_vendas_distrib = QtGui.QGroupBox(self.tab_conf_accera)
        self.grp_accera_vendas_distrib.setCheckable(True)
        self.grp_accera_vendas_distrib.setObjectName(_fromUtf8("grp_accera_vendas_distrib"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.grp_accera_vendas_distrib)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lb_accera_vendas_distrib = QtGui.QLabel(self.grp_accera_vendas_distrib)
        self.lb_accera_vendas_distrib.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_accera_vendas_distrib.setWordWrap(True)
        self.lb_accera_vendas_distrib.setObjectName(_fromUtf8("lb_accera_vendas_distrib"))
        self.verticalLayout_6.addWidget(self.lb_accera_vendas_distrib)
        self.gridLayout_6.addWidget(self.grp_accera_vendas_distrib, 2, 1, 1, 1)
        self.grp_accera_produtos = QtGui.QGroupBox(self.tab_conf_accera)
        self.grp_accera_produtos.setCheckable(True)
        self.grp_accera_produtos.setObjectName(_fromUtf8("grp_accera_produtos"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.grp_accera_produtos)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lb_accera_produtos = QtGui.QLabel(self.grp_accera_produtos)
        self.lb_accera_produtos.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_accera_produtos.setObjectName(_fromUtf8("lb_accera_produtos"))
        self.verticalLayout_3.addWidget(self.lb_accera_produtos)
        self.gridLayout_6.addWidget(self.grp_accera_produtos, 0, 0, 1, 1)
        self.grp_accera_estoque = QtGui.QGroupBox(self.tab_conf_accera)
        self.grp_accera_estoque.setCheckable(True)
        self.grp_accera_estoque.setObjectName(_fromUtf8("grp_accera_estoque"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.grp_accera_estoque)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.rad_accera_estoque_ult_5_dias = QtGui.QRadioButton(self.grp_accera_estoque)
        self.rad_accera_estoque_ult_5_dias.setObjectName(_fromUtf8("rad_accera_estoque_ult_5_dias"))
        self.verticalLayout_5.addWidget(self.rad_accera_estoque_ult_5_dias)
        self.rad_accera_estoque_posicao_atual = QtGui.QRadioButton(self.grp_accera_estoque)
        self.rad_accera_estoque_posicao_atual.setObjectName(_fromUtf8("rad_accera_estoque_posicao_atual"))
        self.verticalLayout_5.addWidget(self.rad_accera_estoque_posicao_atual)
        self.gridLayout_6.addWidget(self.grp_accera_estoque, 2, 0, 1, 1)
        self.grp_accera_cds_lojas = QtGui.QGroupBox(self.tab_conf_accera)
        self.grp_accera_cds_lojas.setCheckable(True)
        self.grp_accera_cds_lojas.setObjectName(_fromUtf8("grp_accera_cds_lojas"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.grp_accera_cds_lojas)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lb_accera_cds_lojas = QtGui.QLabel(self.grp_accera_cds_lojas)
        self.lb_accera_cds_lojas.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_accera_cds_lojas.setObjectName(_fromUtf8("lb_accera_cds_lojas"))
        self.verticalLayout_4.addWidget(self.lb_accera_cds_lojas)
        self.gridLayout_6.addWidget(self.grp_accera_cds_lojas, 0, 1, 1, 1)
        self.grp_accera_clientes = QtGui.QGroupBox(self.tab_conf_accera)
        self.grp_accera_clientes.setCheckable(True)
        self.grp_accera_clientes.setObjectName(_fromUtf8("grp_accera_clientes"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.grp_accera_clientes)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.lb_accera_clientes = QtGui.QLabel(self.grp_accera_clientes)
        self.lb_accera_clientes.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_accera_clientes.setObjectName(_fromUtf8("lb_accera_clientes"))
        self.verticalLayout_7.addWidget(self.lb_accera_clientes)
        self.gridLayout_6.addWidget(self.grp_accera_clientes, 3, 0, 1, 1)
        self.grp_accera_nfe_receb = QtGui.QGroupBox(self.tab_conf_accera)
        self.grp_accera_nfe_receb.setCheckable(True)
        self.grp_accera_nfe_receb.setObjectName(_fromUtf8("grp_accera_nfe_receb"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.grp_accera_nfe_receb)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.lb_accera_nfe_receb = QtGui.QLabel(self.grp_accera_nfe_receb)
        self.lb_accera_nfe_receb.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_accera_nfe_receb.setWordWrap(True)
        self.lb_accera_nfe_receb.setObjectName(_fromUtf8("lb_accera_nfe_receb"))
        self.verticalLayout_8.addWidget(self.lb_accera_nfe_receb)
        self.gridLayout_6.addWidget(self.grp_accera_nfe_receb, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_conf_accera, _fromUtf8(""))
        self.tab_conf_bd = QtGui.QWidget()
        self.tab_conf_bd.setObjectName(_fromUtf8("tab_conf_bd"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_conf_bd)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.grp_conf_bd = QtGui.QGroupBox(self.tab_conf_bd)
        self.grp_conf_bd.setTitle(_fromUtf8(""))
        self.grp_conf_bd.setObjectName(_fromUtf8("grp_conf_bd"))
        self.gridLayout_5 = QtGui.QGridLayout(self.grp_conf_bd)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.cmb_sgbd = QtGui.QComboBox(self.grp_conf_bd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_sgbd.sizePolicy().hasHeightForWidth())
        self.cmb_sgbd.setSizePolicy(sizePolicy)
        self.cmb_sgbd.setEditable(False)
        self.cmb_sgbd.setObjectName(_fromUtf8("cmb_sgbd"))
        self.cmb_sgbd.addItem(_fromUtf8(""))
        self.cmb_sgbd.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cmb_sgbd, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.grp_conf_bd)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.grp_conf_bd)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.grp_conf_bd)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.grp_conf_bd)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 2, 0, 1, 1)
        self.txt_banco = QtGui.QLineEdit(self.grp_conf_bd)
        self.txt_banco.setObjectName(_fromUtf8("txt_banco"))
        self.gridLayout_5.addWidget(self.txt_banco, 5, 1, 1, 1)
        self.txt_servidor = QtGui.QLineEdit(self.grp_conf_bd)
        self.txt_servidor.setObjectName(_fromUtf8("txt_servidor"))
        self.gridLayout_5.addWidget(self.txt_servidor, 1, 1, 1, 1)
        self.txt_usuario = QtGui.QLineEdit(self.grp_conf_bd)
        self.txt_usuario.setEchoMode(QtGui.QLineEdit.Normal)
        self.txt_usuario.setObjectName(_fromUtf8("txt_usuario"))
        self.gridLayout_5.addWidget(self.txt_usuario, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.grp_conf_bd)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 3, 0, 1, 1)
        self.txt_senha = QtGui.QLineEdit(self.grp_conf_bd)
        self.txt_senha.setEchoMode(QtGui.QLineEdit.Password)
        self.txt_senha.setObjectName(_fromUtf8("txt_senha"))
        self.gridLayout_5.addWidget(self.txt_senha, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.grp_conf_bd)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.txt_porta = QtGui.QLineEdit(self.grp_conf_bd)
        self.txt_porta.setMaxLength(4)
        self.txt_porta.setObjectName(_fromUtf8("txt_porta"))
        self.gridLayout_5.addWidget(self.txt_porta, 4, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.grp_conf_bd)
        self.tabWidget.addTab(self.tab_conf_bd, _fromUtf8(""))
        self.tab_gera_ = QtGui.QWidget()
        self.tab_gera_.setObjectName(_fromUtf8("tab_gera_"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_gera_)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.grp_filtro_arq_retroativo = QtGui.QGroupBox(self.tab_gera_)
        self.grp_filtro_arq_retroativo.setObjectName(_fromUtf8("grp_filtro_arq_retroativo"))
        self.gridLayout_7 = QtGui.QGridLayout(self.grp_filtro_arq_retroativo)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.dtFinal = QtGui.QDateEdit(self.grp_filtro_arq_retroativo)
        self.dtFinal.setCalendarPopup(True)
        self.dtFinal.setObjectName(_fromUtf8("dtFinal"))
        self.gridLayout_7.addWidget(self.dtFinal, 0, 2, 1, 1)
        self.dtInicial = QtGui.QDateEdit(self.grp_filtro_arq_retroativo)
        self.dtInicial.setCalendarPopup(True)
        self.dtInicial.setObjectName(_fromUtf8("dtInicial"))
        self.gridLayout_7.addWidget(self.dtInicial, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.grp_filtro_arq_retroativo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_7.addWidget(self.label_9, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.grp_filtro_arq_retroativo)
        self.bt_gerar_arq_retroativo = QtGui.QPushButton(self.tab_gera_)
        self.bt_gerar_arq_retroativo.setObjectName(_fromUtf8("bt_gerar_arq_retroativo"))
        self.verticalLayout_9.addWidget(self.bt_gerar_arq_retroativo)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_gera_, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.bt_testar = QtGui.QPushButton(self.frame)
        self.bt_testar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_testar.setObjectName(_fromUtf8("bt_testar"))
        self.horizontalLayout.addWidget(self.bt_testar)
        self.bt_monitorar = QtGui.QPushButton(self.frame)
        self.bt_monitorar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_monitorar.setObjectName(_fromUtf8("bt_monitorar"))
        self.horizontalLayout.addWidget(self.bt_monitorar)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bt_gravar = QtGui.QPushButton(self.frame)
        self.bt_gravar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_gravar.setObjectName(_fromUtf8("bt_gravar"))
        self.horizontalLayout.addWidget(self.bt_gravar)
        self.bt_sair = QtGui.QPushButton(self.frame)
        self.bt_sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_sair.setObjectName(_fromUtf8("bt_sair"))
        self.horizontalLayout.addWidget(self.bt_sair)
        self.verticalLayout.addWidget(self.frame)
        self.lbl_info = QtGui.QLabel(self.centralwidget)
        self.lbl_info.setText(_fromUtf8(""))
        self.lbl_info.setObjectName(_fromUtf8("lbl_info"))
        self.verticalLayout.addWidget(self.lbl_info)
        self.pbar = QtGui.QProgressBar(self.centralwidget)
        self.pbar.setProperty("value", 0)
        self.pbar.setObjectName(_fromUtf8("pbar"))
        self.verticalLayout.addWidget(self.pbar)
        Principal.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Principal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Principal.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Principal)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Principal.setStatusBar(self.statusbar)

        self.retranslateUi(Principal)
        self.tabWidget.setCurrentIndex(0)
        self.cmb_sgbd.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Principal)
        Principal.setTabOrder(self.dte_hora, self.cmb_fornecedor_accera)
        Principal.setTabOrder(self.cmb_fornecedor_accera, self.bt_add_forn_accera)
        Principal.setTabOrder(self.bt_add_forn_accera, self.tb_fornecedores)
        Principal.setTabOrder(self.tb_fornecedores, self.grp_accera_produtos)
        Principal.setTabOrder(self.grp_accera_produtos, self.grp_accera_cds_lojas)
        Principal.setTabOrder(self.grp_accera_cds_lojas, self.grp_accera_estoque)
        Principal.setTabOrder(self.grp_accera_estoque, self.rad_accera_estoque_ult_5_dias)
        Principal.setTabOrder(self.rad_accera_estoque_ult_5_dias, self.rad_accera_estoque_posicao_atual)
        Principal.setTabOrder(self.rad_accera_estoque_posicao_atual, self.grp_accera_vendas_distrib)
        Principal.setTabOrder(self.grp_accera_vendas_distrib, self.grp_accera_clientes)
        Principal.setTabOrder(self.grp_accera_clientes, self.grp_accera_nfe_receb)
        Principal.setTabOrder(self.grp_accera_nfe_receb, self.cmb_sgbd)
        Principal.setTabOrder(self.cmb_sgbd, self.txt_servidor)
        Principal.setTabOrder(self.txt_servidor, self.txt_usuario)
        Principal.setTabOrder(self.txt_usuario, self.txt_senha)
        Principal.setTabOrder(self.txt_senha, self.txt_porta)
        Principal.setTabOrder(self.txt_porta, self.txt_banco)
        Principal.setTabOrder(self.txt_banco, self.dtInicial)
        Principal.setTabOrder(self.dtInicial, self.dtFinal)
        Principal.setTabOrder(self.dtFinal, self.bt_gerar_arq_retroativo)
        Principal.setTabOrder(self.bt_gerar_arq_retroativo, self.bt_gravar)
        Principal.setTabOrder(self.bt_gravar, self.bt_sair)
        Principal.setTabOrder(self.bt_sair, self.bt_testar)
        Principal.setTabOrder(self.bt_testar, self.bt_monitorar)
        Principal.setTabOrder(self.bt_monitorar, self.tabWidget)
        Principal.setTabOrder(self.tabWidget, self.txt_cod_distrbuidor)

    def retranslateUi(self, Principal):
        Principal.setWindowTitle(_translate("Principal", "Criado por: Ronald Santos / (91) 9 8025-8351 ou ronaldsantos63@gmail.com", None))
        self.grpFornACCERA.setTitle(_translate("Principal", "Fornecedores ACCERA", None))
        self.bt_add_forn_accera.setToolTip(_translate("Principal", "Adiciona o fornecedor ACCERA selecionado no COMBOBOX na tabela", None))
        self.bt_add_forn_accera.setStatusTip(_translate("Principal", "Adiciona o fornecedor ACCERA selecionado no COMBOBOX na tabela de fornecedores ACCERA", None))
        self.bt_add_forn_accera.setWhatsThis(_translate("Principal", "Adiciona o fornecedor ACCERA selecionado no COMBOBOX na tabela", None))
        self.bt_add_forn_accera.setText(_translate("Principal", "+", None))
        self.cmb_fornecedor_accera.setToolTip(_translate("Principal", "Selecione os fornecedores <strong>ACCERA</strong> e pressione <strong>ENTER</strong> ou no botao <strong>+</strong> ao lado para adicionar a lista", None))
        self.cmb_fornecedor_accera.setStatusTip(_translate("Principal", "Selecione os fornecedores ACCERA e pressione ENTER ou no botao + ao lado para adicionar a lista", None))
        self.cmb_fornecedor_accera.setWhatsThis(_translate("Principal", "Selecione os fornecedores ACCERA e pressione ENTER ou no botao + ao lado para adicionar a lista", None))
        self.tb_fornecedores.setToolTip(_translate("Principal", "Tabela de Fornecedores ACCERA", None))
        self.tb_fornecedores.setStatusTip(_translate("Principal", "Tabela de Fornecedores ACCERA", None))
        self.tb_fornecedores.setWhatsThis(_translate("Principal", "Tabela de Fornecedores ACCERA", None))
        item = self.tb_fornecedores.horizontalHeaderItem(0)
        item.setText(_translate("Principal", "Código", None))
        item = self.tb_fornecedores.horizontalHeaderItem(1)
        item.setText(_translate("Principal", "Descrição", None))
        self.grpGeral.setTitle(_translate("Principal", "Geral", None))
        self.label.setText(_translate("Principal", "Hora para gerar arquivos", None))
        self.dte_hora.setToolTip(_translate("Principal", "Define o horário que será gerado os arquivos de integração", None))
        self.dte_hora.setStatusTip(_translate("Principal", "Define o horário que será gerado os arquivos de integração", None))
        self.dte_hora.setWhatsThis(_translate("Principal", "Define o horário que será gerado os arquivos de integração", None))
        self.dte_hora.setDisplayFormat(_translate("Principal", "HH:mm:ss", None))
        self.label_8.setText(_translate("Principal", "Código do Distrbuidor (CNPJ)", None))
        self.txt_cod_distrbuidor.setPlaceholderText(_translate("Principal", "CNPJ do Distribuidor", None))
        self.label_10.setText(_translate("Principal", "Local para gravar os arquivos gerados", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_conf_gerais), _translate("Principal", "Conf. Gerais", None))
        self.grp_accera_vendas_distrib.setToolTip(_translate("Principal", "Vendas do <strong>Distribuidor</strong>", None))
        self.grp_accera_vendas_distrib.setStatusTip(_translate("Principal", "Vendas do Distribuidor", None))
        self.grp_accera_vendas_distrib.setWhatsThis(_translate("Principal", "Vendas do <strong>Distribuidor</strong>", None))
        self.grp_accera_vendas_distrib.setTitle(_translate("Principal", "Vendas Distribuidor", None))
        self.lb_accera_vendas_distrib.setText(_translate("Principal", "Se ativo será gerado diariamente as vendas dos ultimos dias 30 dias", None))
        self.grp_accera_produtos.setToolTip(_translate("Principal", "Cadastro de produtos", None))
        self.grp_accera_produtos.setStatusTip(_translate("Principal", "Cadastro de produtos", None))
        self.grp_accera_produtos.setWhatsThis(_translate("Principal", "Cadastro de produtos", None))
        self.grp_accera_produtos.setTitle(_translate("Principal", "Produtos", None))
        self.lb_accera_produtos.setText(_translate("Principal", "Se ativo será gerado diariamente", None))
        self.grp_accera_estoque.setToolTip(_translate("Principal", "Estoque dos produtos", None))
        self.grp_accera_estoque.setStatusTip(_translate("Principal", "Estoque dos produtos", None))
        self.grp_accera_estoque.setWhatsThis(_translate("Principal", "Estoque dos produtos", None))
        self.grp_accera_estoque.setTitle(_translate("Principal", "Estoque", None))
        self.rad_accera_estoque_ult_5_dias.setText(_translate("Principal", "Ultimos 5 dias", None))
        self.rad_accera_estoque_posicao_atual.setText(_translate("Principal", "Posição atual", None))
        self.grp_accera_cds_lojas.setToolTip(_translate("Principal", "Cadastro de <strong>Centro de Distribuições</strong> ou <strong>Lojas</strong> do distribuidor", None))
        self.grp_accera_cds_lojas.setStatusTip(_translate("Principal", "Cadastro de CENTRO DE DISTRIBUIÇÃO ou LOJAS do distribuidor", None))
        self.grp_accera_cds_lojas.setWhatsThis(_translate("Principal", "Cadastro de CENTRO DE DISTRIBUIÇÃO ou LOJAS do distribuidor", None))
        self.grp_accera_cds_lojas.setTitle(_translate("Principal", "CDs/Lojas", None))
        self.lb_accera_cds_lojas.setText(_translate("Principal", "Se ativo será gerado diaremente ", None))
        self.grp_accera_clientes.setToolTip(_translate("Principal", "Clientes", None))
        self.grp_accera_clientes.setStatusTip(_translate("Principal", "Clientes", None))
        self.grp_accera_clientes.setWhatsThis(_translate("Principal", "Clientes", None))
        self.grp_accera_clientes.setTitle(_translate("Principal", "Clientes", None))
        self.lb_accera_clientes.setText(_translate("Principal", "Se ativo será gerado diariamente", None))
        self.grp_accera_nfe_receb.setToolTip(_translate("Principal", "Notas fiscais de recebidas da ACCERA", None))
        self.grp_accera_nfe_receb.setStatusTip(_translate("Principal", "Notas fiscais de recebidas da ACCERA", None))
        self.grp_accera_nfe_receb.setWhatsThis(_translate("Principal", "Notas fiscais de recebidas da ACCERA", None))
        self.grp_accera_nfe_receb.setTitle(_translate("Principal", "Notas Fiscais Recebidas", None))
        self.lb_accera_nfe_receb.setText(_translate("Principal", "Se ativo será gerado diariamente todas notas fiscais de entrada dos ultimos 30 dias", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_conf_accera), _translate("Principal", "Conf. ACCERA", None))
        self.cmb_sgbd.setToolTip(_translate("Principal", "Sistema de Gerenciamento de Banco de Dados [ Firebird, SQLServer, etc.. ]", None))
        self.cmb_sgbd.setStatusTip(_translate("Principal", "Sistema de Gerenciamento de Banco de Dados [ Firebird, SQLServer, etc.. ]", None))
        self.cmb_sgbd.setWhatsThis(_translate("Principal", "Sistema de Gerenciamento de Banco de Dados [ Firebird, SQLServer, etc.. ]", None))
        self.cmb_sgbd.setItemText(0, _translate("Principal", "Firebird", None))
        self.cmb_sgbd.setItemText(1, _translate("Principal", "SQLServer", None))
        self.label_7.setText(_translate("Principal", "Banco: ", None))
        self.label_3.setText(_translate("Principal", "Servidor: ", None))
        self.label_6.setText(_translate("Principal", "Porta: ", None))
        self.label_4.setText(_translate("Principal", "Usuário: ", None))
        self.txt_banco.setToolTip(_translate("Principal", "Nome ou caminho do banco de dados", None))
        self.txt_banco.setStatusTip(_translate("Principal", "Nome ou caminho do banco de dados", None))
        self.txt_banco.setWhatsThis(_translate("Principal", "Nome ou caminho do banco de dados", None))
        self.txt_banco.setPlaceholderText(_translate("Principal", "Nome ou caminho do banco de dados", None))
        self.txt_servidor.setToolTip(_translate("Principal", "Servidor onde se encontra o SGBD", None))
        self.txt_servidor.setStatusTip(_translate("Principal", "Servidor onde se encontra o SGBD", None))
        self.txt_servidor.setWhatsThis(_translate("Principal", "Servidor onde se encontra o SGBD", None))
        self.txt_servidor.setPlaceholderText(_translate("Principal", "IP ou nome da máquina onde se encontra o banco de dados", None))
        self.txt_usuario.setToolTip(_translate("Principal", "Usuário do SGBD", None))
        self.txt_usuario.setStatusTip(_translate("Principal", "Usuário do SGBD", None))
        self.txt_usuario.setWhatsThis(_translate("Principal", "Usuário do SGBD", None))
        self.txt_usuario.setPlaceholderText(_translate("Principal", "Nome do usuário do banco de dados", None))
        self.label_5.setText(_translate("Principal", "Senha: ", None))
        self.txt_senha.setToolTip(_translate("Principal", "Senha do SGBD", None))
        self.txt_senha.setStatusTip(_translate("Principal", "Senha do SGBD", None))
        self.txt_senha.setWhatsThis(_translate("Principal", "Senha do SGBD", None))
        self.txt_senha.setPlaceholderText(_translate("Principal", "Senha do banco de dados", None))
        self.label_2.setText(_translate("Principal", "SGBD: ", None))
        self.txt_porta.setToolTip(_translate("Principal", "Porta de comunicação com o SGBD", None))
        self.txt_porta.setStatusTip(_translate("Principal", "Porta de comunicação com o SGBD", None))
        self.txt_porta.setWhatsThis(_translate("Principal", "Porta de comunicação com o SGBD", None))
        self.txt_porta.setPlaceholderText(_translate("Principal", "Porta de comunicaçao com o banco de dados", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_conf_bd), _translate("Principal", "Conf. BD", None))
        self.grp_filtro_arq_retroativo.setTitle(_translate("Principal", "Filtro", None))
        self.label_9.setText(_translate("Principal", "Período: ", None))
        self.bt_gerar_arq_retroativo.setText(_translate("Principal", "Gerar arquivos", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_gera_), _translate("Principal", "Gerar Arquivos Retroativos", None))
        self.bt_testar.setToolTip(_translate("Principal", "Gerar arquivos de teste para confirmar se está funcionando as configurações", None))
        self.bt_testar.setStatusTip(_translate("Principal", "Gerar arquivos de teste para confirmar se está funcionando as configurações", None))
        self.bt_testar.setWhatsThis(_translate("Principal", "Gerar arquivos de teste para confirmar se está funcionando as configurações", None))
        self.bt_testar.setText(_translate("Principal", "Testar", None))
        self.bt_monitorar.setToolTip(_translate("Principal", "Iniciar processo de monitoramento", None))
        self.bt_monitorar.setStatusTip(_translate("Principal", "Iniciar processo de monitoramento", None))
        self.bt_monitorar.setWhatsThis(_translate("Principal", "Iniciar processo de monitoramento", None))
        self.bt_monitorar.setText(_translate("Principal", "Iniciar Monitoramento", None))
        self.bt_gravar.setToolTip(_translate("Principal", "Gravar alterações realizadas", None))
        self.bt_gravar.setStatusTip(_translate("Principal", "Gravar alterações realizadas", None))
        self.bt_gravar.setWhatsThis(_translate("Principal", "Gravar alterações realizadas", None))
        self.bt_gravar.setText(_translate("Principal", "Gravar", None))
        self.bt_sair.setToolTip(_translate("Principal", "Fechar aplicação", None))
        self.bt_sair.setStatusTip(_translate("Principal", "Fechar aplicação", None))
        self.bt_sair.setWhatsThis(_translate("Principal", "Fechar aplicação", None))
        self.bt_sair.setText(_translate("Principal", "Sair", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Principal = QtGui.QMainWindow()
    ui = Ui_Principal()
    ui.setupUi(Principal)
    Principal.show()
    sys.exit(app.exec_())

